---
title: "Project GRTS Sampling"
author: "Anna Kurtin"
date: "`r Sys.Date()`"
output: html_document
---


This is a markdown document to create points for a sampling framework 

Currently, the sampling for GRTS is taking too long, so I'm going to try to intersect the LiDAR layer with it before running the GRTS

Info on [EPSG 32100](https://epsg.io/32100) 


```{r Setup, include=FALSE}
# Load in packages
packages <- c("data.table","sf","ggmap","terra","raster","mapview","tidyverse","rgdal","XML","methods","FedData","rasterVis","tidyterra","spsurvey", "spData", "usmap","tmap")
source(".\\R_Scripts\\Install_Load_Packages.R")
load_packages(packages)
```


```{r Establish Bounding Box}
# Bounding box coordinates from MRLC download 2/15:
ymin_proj <- 44.94910
ymax_proj <- 49.03619
xmin_proj <- -112.35849
xmax_proj <- -103.97674

#have to give st_bbox an object
# load in locations data
locs_dat <- fread(".\\Data\\Spatial_Data\\2022_ALLPoints.csv")
locs_dat <- na.omit(locs_dat)
locs_sf <- locs_dat %>% 
  st_as_sf(coords=c("long", "lat")) %>% st_set_crs(32100)
proj_bound <- st_bbox(locs_sf)

# lets reset the boundaries to what we want, the order is"
#xmin, ymin, xmax, ymax
proj_bound[1] <- xmin_proj
proj_bound[2] <- ymin_proj
proj_bound[3] <- xmax_proj
proj_bound[4] <- ymax_proj

```


```{r Read in Reprojected Land Cover Data}
# read in the updated, reprojected raster
lcov <- terra::rast(".\\Data\\Spatial_Data\\NLCD_2019_MTLandcoverProjected.tiff")
lcov <- as.factor(lcov)
# I also made a new raster after setting as factor and changing value but I would just run this code chunk every time lcov_new <- terra::rast(".\\Data\\Spatial_Data\\NLCD_2019_MTLandcoverProjectedEdited.tiff")


# # Working with NLCD data: https://smalltownbigdata.github.io/feb2021-landcover/feb2021-landcover.html
# # load in the legend 
legend <- pal_nlcd()
#lcov_test <- merge(lcov, df, by = "ID")
#lcov_test <- lcov
vals <- unique(lcov[[1]])
# # pull out the values of the legend that are in the values of my map
df <- legend[legend$ID %in% vals$label,]
levels(lcov) <- df[,c("ID","Class")]
# need to relate the colors that it plots the raster to specific variables 
colors=c("#5475A8","#FFFFFF","#E8D1D1","#E29E8C","#ff0000","#B50000","#D2CDC0","#85C77E","#38814E","#D4E7B0","#DCCA8F","#FDE9AA","#FBF65D","#CA9146","#C8E6F8","#64B3D5")
plot(lcov)



# Matrix of numbers that correspond to landcover values
cats <- matrix(nrow=20, ncol=2)
colnames(cats) <- c("ID","Landcover")
# input the corresponding values from the dataframe
cats[,1] <- legend$ID
cats[,2] <- legend$Class
length(legend$ID)
#need to remove dwarf scrub, sedge/herbaceous, lichens, moss
# cats[,1] <- c(11,12, 21, 22,23, 24, 31, 41, 42, 43, 52, 71, 81, 82, 90,95)
# # #match these up with the values from the land cover
# cats[,2] <- c("open_water","ice_snow","developed_open","developed_low","developed_med","developed_high","barren","deciduous_forest","evergreen_forest","mixed_forest","shrub_scrub","grasslands_herbaceous","pasture_hay","woody_wetlands","herbaceous_wetlands")
```

```{r Create Buffer Raster from Vector Data}
# Read in hydrology layer
hydro <- st_read("D:\\MT_Spatial_Data\\MT_Lakes_Streams\\hd43a\\hd43a.shp")
# Combined study area
names <- c("Missouri River","Yellowstone River","Musselshell River")
proj_hydro <- hydro %>% filter(NAME %in% names)
proj_hydro <- proj_hydro %>% dplyr::select(NAME, geometry)
# Separate by river
hydro_miso <- hydro %>% filter(NAME == "Missouri River") %>% dplyr::select(NAME, geometry)
hydro_mush <- hydro %>% filter(NAME == "Musselshell River") %>% dplyr::select(NAME, geometry)
hydro_yell <- hydro %>% filter(NAME == "Yellowstone River") %>% dplyr::select(NAME, geometry)

# Create a buffer layer for each river
buff_miso <- st_buffer(hydro_miso, dist = 400)
buff_mush <- st_buffer(hydro_mush, dist = 400)
buff_yell <- st_buffer(hydro_yell, dist = 400)

# Mask land cover to only within the hydrology 
# write these as rasters after you're done
#lcov_miso <- mask(lcov,buff_miso)
#terra::writeRaster(lcov_miso,"Data\\Spatial_Data\\NLCD_2019_MissouriLandcover.tiff")
#lcov_mush <- mask(lcov,buff_mush)
#terra::writeRaster(lcov_mush,"Data\\Spatial_Data\\NLCD_2019_MusselshellLandcover.tiff")
#lcov_yell <- mask(lcov,buff_yell)
#terra::writeRaster(lcov_yell,"Data\\Spatial_Data\\NLCD_2019_YellowstoneLandcover.tiff")


total_arus <- 45
# base sample is 15 along each river
```

```{r}
# read in land cover data for each river 
lcov_miso <- terra::rast("D:\\MT_Spatial_Data\\For_GRTS\\NLCD_2019_MissouriLandcover.tiff")
lcov_mush <- terra::rast("D:\\MT_Spatial_Data\\For_GRTS\\NLCD_2019_MusselshellLandcover.tiff")
lcov_yell <- terra::rast("D:\\MT_Spatial_Data\\For_GRTS\\NLCD_2019_YellowstoneLandcover.tiff")

```

```{r Mask for LiDAR Data}
#1. initialize the raster
mask_raster <- rast()
#2. set extent (note that I customized this extent so it covered both elc_habitat and humanacess) (this usually requires some research to set your bounding box)
ext(mask_raster) <- c(xmin=xmin_proj, xmax=xmax_proj, ymin=ymin_proj, ymax=ymax_proj) 	
#3. set the resolution to 300 m - this is really large, set it to one instead
res(mask_raster)<- 1
#4.get the projection you're working with
crs(mask_raster)<- "EPSG:32100"

# check it
res(mask_raster)
ext(mask_raster)
```



GRTS Sampling

```{r Musselshell}
# RUN ONCE
## convert Spatraster to a raster object
lcov_mush <- terra::rast("E:\\MT_Spatial_Data\\For_GRTS\\NLCD_2019_MusselshellLandcover_MaskedToLidar.tiff")
system.time(lcovrast_mush <- raster(lcov_mush))
## convert raster to polygons
system.time(lcovpoly_mush <- rasterToPolygons(lcovrast_mush))
## DONT RUN THIS AGAIN
## make a shapefile of the polygon
shapefile(lcovpoly_mush, "E:\\MT_Spatial_Data\\For_GRTS\\Landcover_Polygon_Musselshell_MaskedToRaster.shp")

# read in the shapefile and make sure it is in a projected (not geographic) coordinate system
#polys_mush <- st_read(".\\Data\\Spatial_Data\\Landcover_Polygon_Musselshell.shp") 

polys_mush <- st_read("E:\\MT_Spatial_Data\\For_GRTS\\Landcover_Polygon_Musselshell_MaskedToRaster.shp") 

lcov_to_exclude <- c(11,12,21,22,23,24,31,81,82)

# create a list of the number of the samples you want for each strata
## NOTE you can't specify zero for this, put in 1 for the ones you don't want
# adjust this as needed later
n_strata <- c("11"=1,
              "21"=1,
              "22"=1,
              "23"=1,
              "41"=3,
              "42"=3,
              "43"=3,
              "52"=3,
              "71"=3,
              "81"=1,
              "82"=1,
              "90"=3,
              "95"=3)

## Say how many over samples you want for each strata
## here is where you can put zero in for classes you don't want 
n_oversamp <- c("11"=0,
              "21"=0,
              "22"=0,
              "23"=0,
              "41"=30,
              "42"=30,
              "43"=30,
              "52"=30,
              "71"=30,
              "81"=0,
              "82"=0,
              "90"=30,
              "95"=30)

# set the seed before running your sampling protocol so that you get the same randomness every time
## you can change this if you don't like how the distributions look 
set.seed(13)
#unique(polys_mush$Class)

# set up your GRTS function
sampling_pts <- grts(sframe=polys_mush,
                     n_base=n_strata,# creates a list of the strata and how many points within each strata
                     stratum_var="Class", # what the ID/column in polygon data is that you're stratifying by 
                     n_over=n_oversamp) # gives you your extra spatially balanced points

# extract the main sampling points as a tibble
main_sampling_points <- as_tibble(sampling_pts$sites_base)
write.csv(main_sampling_points,"E:\\MT_Spatial_Data\\Mush_Main_Sample_MaskedToLiDAR.csv")
# extract the over sampled points
over_sampling_points <- as_tibble(sampling_pts$sites_over)
write.csv(over_sampling_points,"E:\\MT_Spatial_Data\\Mush_Over_Sample_MaskedToLiDAR.csv")

# filter out the strata that we don't want (the ones we had to specify to only sample one of)
#main_samples_trimmed <- main_sampling_points %>% filter(!strata %in% lancov_to_exclude)
# add in a column for the names of each column 
#main_samples_trimmed <- main_samples_trimmed %>% mutate(lancover == )
```

```{r Yellowstone}
# RUN ONCE
lcov_yell_small <- terra::rast("E:\\MT_Spatial_Data\\For_GRTS\\NLCD_2019_YellowstoneLandcover_MaskedToLidar_NoPark.tiff")
# ## convert Spatraster to a raster object
lcov_yell_small_rast <- raster(lcov_yell_small)
# ## convert raster to polygons
system.time(lcovpoly_yell <- rasterToPolygons(lcov_yell_small_rast))
# ## DONT RUN THIS AGAIN
# ## make a shapefile of the polygon
shapefile(lcovpoly_yell, "E:\\MT_Spatial_Data\\For_GRTS\\Landcover_Polygon_Yellowstone_MaskedToLidar_NoPark.shp")

# read in the shapefile and make sure it is in a projected (not geographic) coordinate system
polys_yell <- st_read("E:\\MT_Spatial_Data\\For_GRTS\\Landcover_Polygon_Yellowstone_MaskedToLidar_NoPark.shp") 

lcov_to_exclude <- c(11,12,21,22,23,24,31,81,82)

# create a list of the number of the samples you want for each strata
## NOTE you can't specify zero for this, put in 1 for the ones you don't want
# adjust this as needed later
n_strata <- c("11"=1,
              "21"=1,
              "22"=1,
              "23"=1,
              "24"=1,
              "31"=1,
              "41"=3,
              "42"=3,
              "43"=3,
              "52"=3,
              "71"=3,
              "81"=1,
              "82"=1,
              "90"=3,
              "95"=3)

## Say how many over samples you want for each strata
## here is where you can put zero in for classes you don't want 
n_oversamp <- c("11"=0,
              "21"=0,
              "22"=0,
              "23"=0,
              "24"=0,
              "31"=0,
              "41"=30,
              "42"=30,
              "43"=30,
              "52"=30,
              "71"=30,
              "81"=0,
              "82"=0,
              "90"=30,
              "95"=30)

# set the seed before running your sampling protocol so that you get the same randomness every time
## you can change this if you don't like how the distributions look 
set.seed(13)
#unique(polys_yell$Class)

# set up your GRTS function
sampling_pts <- grts(sframe=polys_yell,
                     n_base=n_strata,# creates a list of the strata and how many points within each strata
                     stratum_var="Class", # what the ID/column in polygon data is that you're stratifying by 
                     n_over=n_oversamp) # gives you your extra spatially balanced points

# extract the main sampling points as a tibble
main_sampling_points <- as_tibble(sampling_pts$sites_base)
write.csv(main_sampling_points, "E:\\MT_Spatial_Data\\Yell_Main_Sample_MakedToLidar.csv")
# extract the over sampled points
over_sampling_points <- as_tibble(sampling_pts$sites_over)
write.csv(over_sampling_points, "E:\\MT_Spatial_Data\\Yell_Over_Sample_MakedToLidar.csv")

# # filter out the strata that we don't want (the ones we had to specify to only sample one of)
# main_samples_trimmed <- main_sampling_points %>% filter(!strata %in% lancov_to_exclude)
# # add in a column for the names of each column 
# main_samples_trimmed <- main_samples_trimmed %>% mutate(lancover == )
```


```{r Landcov To Exclude from GRTS}
# Set up which land cover you want to exclude from the sample 
lcov_to_exclude <- c(11,12,21,22,23,24,31,81,82)
# should I be excluding cultivated crops?
# if not, could we include shelter belts in the crops area? Might be a question for FWP


```


```{r Missouri GRTS Plotting}
# select the points in the GRTS sample we want
miso_main <- read_csv("D:\\MT_Spatial_Data\\Miso_Main_Sample.csv")
miso_main_trim <- miso_main %>% filter(!stratum %in% lcov_to_exclude)
# make it into an SF object
miso_main_sf <- miso_main_trim %>% st_as_sf(coords=c("lon_WGS84", "lat_WGS84")) %>%
  st_set_crs("EPSF:32100")

miso_over <- read_csv("D:\\MT_Spatial_Data\\Miso_Over_Sample.csv")
# no need to trim in the over sample 
# make it into an SF object
miso_over_sf <- miso_over %>% st_as_sf(coords=c("lon_WGS84", "lat_WGS84")) %>%
  st_set_crs("EPSF:32100")


polys_miso <- st_read("D:\\MT_Spatial_Data\\For_GRTS\\Landcover_Polygon_Missouri.shp") 

# add in a column for the names of each column 
#main_samples_trimmed <- main_samples_trimmed %>% mutate(lancover == 1)



# visualize them with the land cover data - assess the distribution 

# Transform lcov into a raster
lcov_miso_rast <- raster(lcov_miso)

# plot it to check what it's doing
mapview(miso_main_sf)

# # map the land cover and the sf layer together 
# miso_list <- list(miso_main_sf,lcov_miso_rast)
# mapView(miso_list,color=lcov_miso_rast$Class)
# # there are too many pixels in the land cover data - try intersecting this with the LiDAR data
# plot(lcov_miso)
# plot(miso_main_sf$geometry,add=TRUE)
# # can't tell if this added what I wanted
lcov_miso_raster <- raster(lcov_miso)
# miso <- list(lcov_miso_raster,miso_main_sf)
# mapview(lcov_miso_raster)


# try plotting using tmap
tmap_mode("view") # set to "plot" for static plotting, set to "view" for interactive plots
tm_shape(polys_miso) + tm_sf() # this didn't work with the spatraster object


tm_shape(lcov_miso_raster) + tm_sf()
# this takes a while to plot - try this later

# figure out plotting with this 
# how to add on sf object to this?
ggplot()+
  geom_spatraster(data = lcov_miso) + 
  scale_fill_manual(values=colors)+
  geom_sf(data=miso_main_sf)

# intersect with LiDAR

# visualize with cadastrel data

# have a prety output I guess
```




